---
version: "3"
services:
  server:
    image: molguin/edgedroid2:server
    container_name: server
    hostname: server
    volumes:
      - "./results:/opt/results:rw"
    command:
      - "--output"
      - "/opt/results/server_${MODEL}.csv"
      - "--verbose"
      - "0.0.0.0"
      - "5000"
      - "${TASK}"
    restart: "no"
  client:
    image: molguin/edgedroid2:client
    container_name: client
    hostname: client
    volumes:
      - "./results:/opt/results:rw"
    command:
      - "-n"
      - "0.5"
      - "-t"
      - "${TASK}"
      - "-f"
      - "8"
      - "-m"
      - "${MODEL}"
      - "-o"
      - "/opt/results/client_${MODEL}.csv"
      - "--verbose"
      - "server"
      - "5000"
    depends_on:
      - server
    restart: "no"