---
name: "Unit Testing"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install -U ".[all]"
      - name: Run unit tests
        run: python -m unittest discover -vvvvv edgedroid.tests
...